"""
MCIFT v1.09 candidate:
Second-tetrahedron mass gain while influenced by an older/heavier T0.

Goal
----
Test whether a relational "down" direction can arise DURING T1 mass gain,
without inserting an apex-alignment force.

T0:
    fixed at origin
T1 center:
    fixed at R0 for this formation-only test
T1:
    four free vertices + four face-vortex amplitudes

The v1.08 intrinsic energy is retained:
    F_f = A_f [ 1/2 (c Q_f - k_f) Omega_f^2 + 1/4 Omega_f^4 ]

The new ingredient is only a spatially varying drive generated by T0:
    Phi0(x) = S0 / |x|

Two ways of feeding that field into the four face drives are compared:

A) face_centroid_field
    k_f = k_self + Phi0(face centroid)

B) vertex_sampled_field
    k_f = k_self + mean_{v in face} Phi0(vertex v)

No apex target, alignment spring, target side length, target volume,
or global up/down direction is used.

k_self is slowly ramped upward to represent T1 mass gain. At each ramp point
the code finds the local equilibrium branch from the previous state. The
optimizer is a numerical equilibrium solver, not physical damping.

This is a toy structural test only.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from scipy.spatial.transform import Rotation

torch.set_default_dtype(torch.float64)

HERE = Path(__file__).resolve().parent
METRICS_PATH = HERE / "mcift_v109_second_tetrahedron_mass_gain_metrics.json"
TRACE_PATH = HERE / "mcift_v109_second_tetrahedron_mass_gain_trace.csv"

C_TRI = 27.0 / 2800.0
R0 = 6.0
SOURCE_STRENGTH = 0.5
K_RAMP = np.linspace(-0.05, 0.20, 7)

FACES = [(1,2,3),(0,2,3),(0,1,3),(0,1,2)]
UNIT_REGULAR = np.array(
    [[1,1,1],[1,-1,-1],[-1,1,-1],[-1,-1,1]], float
) / (2.0 * math.sqrt(2.0))


def centered_world_vertices(y):
    Xrel = y[:12].reshape(4,3)
    Xrel = Xrel - Xrel.mean(dim=0)
    center = torch.tensor([R0,0.0,0.0], dtype=y.dtype)
    return Xrel + center, Xrel


def energy(y, k_self, mode, source_strength):
    X, _ = centered_world_vertices(y)
    omega = y[12:]
    total = torch.zeros((), dtype=y.dtype)

    phi_v = source_strength / torch.linalg.norm(X, dim=1)

    for fi, f in enumerate(FACES):
        P = X[list(f)]
        centroid = P.mean(dim=0)
        q = P - centroid
        Q = (q*q).sum()
        A = 0.5 * torch.linalg.norm(
            torch.cross(P[1]-P[0], P[2]-P[0], dim=0)
        )

        if source_strength == 0:
            phi = torch.zeros((), dtype=y.dtype)
        elif mode == "face_centroid_field":
            phi = source_strength / torch.linalg.norm(centroid)
        elif mode == "vertex_sampled_field":
            phi = phi_v[list(f)].mean()
        else:
            raise ValueError(mode)

        kf = k_self + phi
        total = total + A * (
            0.5 * (C_TRI*Q - kf) * omega[fi]**2
            + 0.25 * omega[fi]**4
        )
    return total


def solve_step(y_np, k_self, mode, source_strength):
    y = torch.tensor(y_np, requires_grad=True)
    opt = torch.optim.LBFGS(
        [y],
        lr=0.8,
        max_iter=140,
        tolerance_grad=1e-10,
        tolerance_change=1e-12,
        line_search_fn="strong_wolfe",
    )

    def closure():
        opt.zero_grad()
        loss = energy(y, k_self, mode, source_strength)
        loss.backward()
        return loss

    opt.step(closure)
    return y.detach().numpy()


def state_metrics(y_np, k_self, mode, source_strength):
    y = torch.tensor(y_np)
    Xw, Xrel_t = centered_world_vertices(y)
    Xw = Xw.detach().numpy()
    Xrel = Xrel_t.detach().numpy()
    omega = y_np[12:]

    inward = np.array([-1.0,0.0,0.0])

    apex_scores = Xrel @ inward / np.linalg.norm(Xrel, axis=1)
    apex_idx = int(np.argmax(apex_scores))
    apex_score = float(apex_scores[apex_idx])

    face_centroids_rel = np.array(
        [Xrel[list(f)].mean(axis=0) for f in FACES]
    )
    face_scores = (
        face_centroids_rel @ inward
        / np.linalg.norm(face_centroids_rel, axis=1)
    )
    face_idx = int(np.argmax(face_scores))
    face_score = float(face_scores[face_idx])

    edges = np.array(
        [np.linalg.norm(Xrel[i]-Xrel[j])
         for i in range(4) for j in range(i+1,4)]
    )
    M = np.stack(
        [Xrel[1]-Xrel[0], Xrel[2]-Xrel[0], Xrel[3]-Xrel[0]],
        axis=1
    )
    volume = abs(np.linalg.det(M))/6.0

    k_faces = []
    positive_mass_terms = []
    for fi, f in enumerate(FACES):
        P = Xw[list(f)]
        centroid = P.mean(axis=0)
        q = P-centroid
        Q = float((q*q).sum())
        A = 0.5*np.linalg.norm(np.cross(P[1]-P[0], P[2]-P[0]))

        if source_strength == 0:
            phi = 0.0
        elif mode == "face_centroid_field":
            phi = source_strength/np.linalg.norm(centroid)
        else:
            phi = np.mean(source_strength/np.linalg.norm(P,axis=1))

        kf = k_self + phi
        k_faces.append(kf)

        positive_mass_terms.append(
            0.5*C_TRI*Q*A*omega[fi]**2
            + 0.25*A*omega[fi]**4
        )

    return {
        "apex_score": apex_score,
        "apex_vertex": apex_idx,
        "face_score": face_score,
        "inward_face": face_idx,
        "mean_edge": float(edges.mean()),
        "edge_cv": float(edges.std()/edges.mean()),
        "volume": float(volume),
        "mass_proxy": float(np.sum(positive_mass_terms)),
        "omega_mean": float(np.mean(omega)),
        "omega_std": float(np.std(omega)),
        "omega_faces": [float(x) for x in omega],
        "k_faces": [float(x) for x in k_faces],
        "drive_spread": float(np.max(k_faces)-np.min(k_faces)),
    }


def initial_state(seed):
    rng = np.random.default_rng(seed)
    R = Rotation.random(random_state=rng).as_matrix()
    edge0 = 0.8
    Xrel = UNIT_REGULAR * edge0 @ R.T
    Xrel += rng.normal(scale=1e-4, size=Xrel.shape)
    Xrel -= Xrel.mean(axis=0)
    omega = np.full(4, 0.02)
    return np.concatenate([Xrel.ravel(), omega])


def run_branch(seed, mode, source_strength):
    y = initial_state(seed)
    rows = []
    for step, k_self in enumerate(K_RAMP):
        y = solve_step(y, float(k_self), mode, source_strength)
        m = state_metrics(y, float(k_self), mode, source_strength)
        rows.append({
            "seed": seed,
            "mode": mode if source_strength else "no_source_control",
            "step": step,
            "k_self": float(k_self),
            **{k:v for k,v in m.items()
               if k not in ("omega_faces","k_faces")},
            "omega_faces": json.dumps(m["omega_faces"]),
            "k_faces": json.dumps(m["k_faces"]),
        })
    return y, rows, state_metrics(
        y, float(K_RAMP[-1]), mode, source_strength
    )


def classify(m):
    if m["apex_score"] > 0.95 and m["face_score"] < 0.75:
        return "APEX_INWARD"
    if m["face_score"] > 0.95 and m["apex_score"] < 0.75:
        return "FACE_INWARD"
    return "MIXED"


def main():
    seeds = [11, 22, 33, 44]
    all_rows = []
    finals = {
        "face_centroid_field": [],
        "vertex_sampled_field": [],
        "no_source_control": [],
    }

    for mode in ["face_centroid_field","vertex_sampled_field"]:
        for seed in seeds:
            _, rows, final = run_branch(seed, mode, SOURCE_STRENGTH)
            all_rows.extend(rows)
            final["seed"] = seed
            final["classification"] = classify(final)
            finals[mode].append(final)

    for seed in seeds:
        _, rows, final = run_branch(seed, "vertex_sampled_field", 0.0)
        all_rows.extend(rows)
        final["seed"] = seed
        final["classification"] = classify(final)
        finals["no_source_control"].append(final)

    pd.DataFrame(all_rows).to_csv(TRACE_PATH, index=False)

    summary = {}
    for key, vals in finals.items():
        summary[key] = {
            "classifications": [v["classification"] for v in vals],
            "apex_scores": [v["apex_score"] for v in vals],
            "face_scores": [v["face_score"] for v in vals],
            "edge_cv": [v["edge_cv"] for v in vals],
            "volumes": [v["volume"] for v in vals],
            "mass_proxy": [v["mass_proxy"] for v in vals],
            "drive_spread": [v["drive_spread"] for v in vals],
            "representative_omega_faces": vals[0]["omega_faces"],
            "representative_k_faces": vals[0]["k_faces"],
        }

    metrics = {
        "status": (
            "T0_BIASED_MASS_GAIN_SELECTS_APEX_INWARD_ONLY_WHEN_SOURCE_FIELD_"
            "IS_SAMPLED_AT_VERTICES_BEFORE_FEEDING_FACE_VORTICES"
        ),
        "scope": {
            "physical_higgs_claim": False,
            "physical_gravity_claim": False,
            "physical_mass_claim": False,
            "formation_center_fixed": True,
            "orbit_tested_here": False,
            "alignment_spring_used": False,
            "target_side_length_used": False,
            "target_volume_used": False,
            "global_down_used": False,
            "optimizer_is_equilibrium_solver_not_physical_damping": True,
        },
        "parameters": {
            "T1_center_distance": R0,
            "normalized_source_strength_gamma_M0": SOURCE_STRENGTH,
            "k_self_ramp": [float(x) for x in K_RAMP],
            "random_orientation_seeds": seeds,
        },
        "results": summary,
        "interpretation": (
            "During quasi-static mass gain, a source field from older/heavier T0 "
            "provides a relational radial gradient. If that field is sampled at "
            "face centroids, T1 converges face-inward. If it is sampled at the "
            "vertices and each face receives the average field of its three bounding "
            "vertices, T1 converges apex-inward from every tested random orientation. "
            "The no-source control has no universal inward orientation. This is a "
            "candidate derived mechanism for the pyramid direction, but it does not "
            "yet establish that physical MCIFT inter-cell coupling is vertex-sampled."
        ),
    }

    METRICS_PATH.write_text(json.dumps(metrics, indent=2), encoding="utf-8")

    print(json.dumps({
        "status": metrics["status"],
        "summary": summary,
    }, indent=2))


if __name__ == "__main__":
    main()
